apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: ""
      lokiSearch:
        datasourceUid: ""
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
